baseURL = "https://kimsellis.com/"
languageCode = "en-us"
title = "Kim Sellis Yoga"

enableRobotsTXT = true
theme = "terrassa"      # Your Hugo theme

[params.separator]
    show = true

[params.cta] # Call To Action
    show = true
    cta = "Book Now"  # Text message of the CTA
    link = "classes" # Relative URL

[params.terms]
    privacy = "/privacy"
    tandc = "/terms/"

[params.fa] # Font Awesome options
    version = "5.7.2"
    integrity = "sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP"


[params.form] # Contact form
    netlify = false
    action = "https://kimsellis.us16.list-manage.com/subscribe/post?u=65fa1e93f0f327bfd39550cd4&amp;id=5399e395ca"
    method = "POST"
    inputFNameName = "FNAME"
    inputFNameLabel = "First Name"
    inputFNamePlaceholder = ""
    inputLNameName = "LNAME"
    inputLNameLabel = "Family Name"
    inputLNamePlaceholder = ""
    inputPhoneName = "MMERGE4"
    inputPhoneLabel = "Phone number"
    inputPhonePlaceholder = ""
    inputEmailName = "EMAIL"
    inputEmailLabel = "Email*"
    inputEmailPlaceholder = ""
    inputSubmitValue = "Subscribe"



[params.contact] # Contact info
    email = "yoga@kimsellis.com"


